#################################################################
#
# Build configuration file template for EPREM.
#
#################################################################
# Enter your C MPI wrapper (e.g. "mpicc", "mpicx", etc.).
#################################################################

CC: 

###########################################################################
# Please set the compile flags based on your compiler and hardware setup.
###########################################################################

CCFLAGS: 
CCLDFLAGS:

#################################################################
# Set location of required include & library files and flags.
#################################################################

HDF5_INCLUDE_DIR: 
HDF5_LIB_DIR: 
HDF5_LIB_FLAGS: 

NETCDF_INCLUDE_DIR:
NETCDF_LIB_DIR:
NETCDF_LIB_FLAGS:

LIBCONFIG_INCLUDE_DIR:
LIBCONFIG_LIB_DIR:
LIBCONFIG_LIB_FLAGS:

#################################################################
