#################################################################
#
# Build configuration file template for EPREM.
#
#################################################################
# Enter your C MPI wrapper (e.g. "mpicc", "mpicx", etc.).
#################################################################

CC: mpicc

###########################################################################
# Please set the compile flags based on your compiler and hardware setup.
###########################################################################

CCFLAGS: -O3 -march=native -Wall -Wextra -std=c99
CCLDFLAGS: -lm

#################################################################
# Set location of required include & library files and flags.
#################################################################

HDF5_INCLUDE_DIR: /usr/include/hdf5/serial
HDF5_LIB_DIR: .
HDF5_LIB_FLAGS: -lhdf5_serial_fortran -lhdf5_serialhl_fortran -lhdf5_serial -lhdf5_serial_hl

NETCDF_INCLUDE_DIR: .
NETCDF_LIB_DIR: .
NETCDF_LIB_FLAGS: -lnetcdf

LIBCONFIG_INCLUDE_DIR: .
LIBCONFIG_LIB_DIR: .
LIBCONFIG_LIB_FLAGS: -lconfig

#################################################################
