#################################################################
#
# Build configuration file template for EPREM.
#
#################################################################
# Enter your C MPI wrapper (e.g. "mpicc", "mpicx", etc.).
#################################################################

CC: mpiicx

###########################################################################
# Please set the compile flags based on your compiler and hardware setup.
###########################################################################

CCFLAGS: -O3 -xHost -fp-model precise 
CCLDFLAGS: 

#################################################################
# Set location of required include & library files and flags.
#################################################################

HDF5_INCLUDE_DIR: ${PS_EXT_DEPS_HOME}/hdf5/include
HDF5_LIB_DIR: ${PS_EXT_DEPS_HOME}/hdf5/lib
HDF5_LIB_FLAGS: -lhdf5_fortran -lhdf5hl_fortran -lhdf5 -lhdf5_hl

NETCDF_INCLUDE_DIR: ${PS_EXT_DEPS_HOME}/netcdf/include
NETCDF_LIB_DIR: ${PS_EXT_DEPS_HOME}/netcdf/lib
NETCDF_LIB_FLAGS: -lnetcdf

LIBCONFIG_INCLUDE_DIR: ${PS_EXT_DEPS_HOME}/libconfig/include
LIBCONFIG_LIB_DIR: ${PS_EXT_DEPS_HOME}/libconfig/lib
LIBCONFIG_LIB_FLAGS: -lconfig

#################################################################
