#!/bin/bash
#################################################################
# Please set the location of include/library files and
#  linker flags to match your installed version.
#
# Build script template for EPREM.
#
# See the build scripts in the "/build_examples" 
# folder for examples of what to insert here.
# Please do not edit this file, rather copy it to a new 
# file with your own configuration options inserted.
# If your configuration is unique, feel free to add it to the 
# /build_examples folder.
# Note that your build script must be launched from 
# this lowest level directory (not from the build_examples folder).
#
#################################################################
# Enter your MPI compiler wrapper (typically "mpicc").
#################################################################

CC=mpicc

###########################################################################
# Please set the compile flags based on your compiler and hardware setup.
###########################################################################

CFLAGS="-O3 -march=native -std=c99"
CC_LD_OPTS="-lm"

#################################################################
# Please set the location of the include & library files. 
# Make sure the librariesa are COMPILED with 
# the SAME COMPILER used here, and is in the run-time environment.
#################################################################

HDF5_INCLUDE_DIR=${PS_EXT_DEPS_HOME}/hdf5/include
HDF5_LIB_DIR=${PS_EXT_DEPS_HOME}/hdf5/lib
HDF5_LIB_FLAGS="-lhdf5hl_fortran -lhdf5_hl -lhdf5_fortran -lhdf5"

HDF4_INCLUDE_DIR=${PS_EXT_DEPS_HOME}/hdf4/include
HDF4_LIB_DIR=${PS_EXT_DEPS_HOME}/hdf4/lib
HDF4_LIB_FLAGS="-lmfhdf -ldf -ljpeg -lz -ltirpc"

ZLIB_INCLUDE_DIR=${PS_EXT_DEPS_HOME}/zlib/include
ZLIB_LIB_DIR=${PS_EXT_DEPS_HOME}/zlib/lib

JPEG_INCLUDE_DIR=${PS_EXT_DEPS_HOME}/jpeg/include
JPEG_LIB_DIR=${PS_EXT_DEPS_HOME}/jpeg/lib

NETCDF_INCLUDE_DIR=${PS_EXT_DEPS_HOME}/netcdf/include
NETCDF_LIB_DIR=${PS_EXT_DEPS_HOME}/netcdf/lib
NETCDF_LIB_FLAGS="-lnetcdf -lz"

LIBCONFIG_INCLUDE_DIR=${PS_EXT_DEPS_HOME}/libconfig/include
LIBCONFIG_LIB_DIR=${PS_EXT_DEPS_HOME}/libconfig/lib
LIBCONFIG_LIB_FLAGS="-lconfig"

###########################################################################
###########################################################################
###########################################################################

EPREM_HOME=$PWD

cX="\033[0m"
cR="\033[1;31m"
cB="\033[1;34m"
cG="\033[32m"
cC="\033[1;96m"
cM="\033[35m"
cY="\033[1;93m"
Bl="\033[1;5;96m"
echo="echo -e"

${echo} "${cG}=== STARTING EPREM BUILD ===${cX}"
${echo} "==> Entering src directory..."
pushd ${EPREM_HOME}/src > /dev/null
${echo} "==> Removing old Makefile..."
if [ -e Makefile ]; then
  \rm Makefile
fi 
${echo} "==> Generating Makefile from Makefile.template..."
sed \
  -e "s#<CC>#${CC}#g" \
  -e "s#<CFLAGS>#${CFLAGS}#g" \
  -e "s#<CC_LD_OPTS>#${CC_LD_OPTS}#g" \
  -e "s#<HDF5_INCLUDE_DIR>#${HDF5_INCLUDE_DIR}#g" \
  -e "s#<HDF5_LIB_DIR>#${HDF5_LIB_DIR}#g" \
  -e "s#<HDF5_LIB_FLAGS>#${HDF5_LIB_FLAGS}#g" \
  -e "s#<HDF4_INCLUDE_DIR>#${HDF4_INCLUDE_DIR}#g" \
  -e "s#<HDF4_LIB_DIR>#${HDF4_LIB_DIR}#g" \
  -e "s#<HDF4_LIB_FLAGS>#${HDF4_LIB_FLAGS}#g" \
  -e "s#<ZLIB_INCLUDE_DIR>#${ZLIB_INCLUDE_DIR}#g" \
  -e "s#<ZLIB_LIB_DIR>#${ZLIB_LIB_DIR}#g" \
  -e "s#<JPEG_INCLUDE_DIR>#${JPEG_INCLUDE_DIR}#g" \
  -e "s#<JPEG_LIB_DIR>#${JPEG_LIB_DIR}#g" \
  -e "s#<NETCDF_INCLUDE_DIR>#${NETCDF_INCLUDE_DIR}#g" \
  -e "s#<NETCDF_LIB_DIR>#${NETCDF_LIB_DIR}#g" \
  -e "s#<NETCDF_LIB_FLAGS>#${NETCDF_LIB_FLAGS}#g" \
  -e "s#<LIBCONFIG_INCLUDE_DIR>#${LIBCONFIG_INCLUDE_DIR}#g" \
  -e "s#<LIBCONFIG_LIB_DIR>#${LIBCONFIG_LIB_DIR}#g" \
  -e "s#<LIBCONFIG_LIB_FLAGS>#${LIBCONFIG_LIB_FLAGS}#g" \
  Makefile.template > Makefile
${echo} "==> Compiling code..."
make clean 1>/dev/null 2>/dev/null ; make 1>build.log 2>build.err
if [ ! -e eprem ]; then
  ${echo} "${cR}!!> ERROR!  eprem executable not found.  Build most likely failed."
  ${echo} "            Contents of src/build.err:"
  cat build.err
  ${echo} "${cX}"
  exit 1
fi
${echo} "==> Copying eprem executable to: ${EPREM_HOME}/bin/eprem"
cp eprem ${EPREM_HOME}/bin/eprem
${echo} "${cG}==> Build complete!${cX}"
${echo}      "    Please add the following to your shell startup (e.g. .bashrc, .profile, etc.):"
${echo} "${cC}    export PATH=${EPREM_HOME}/bin:\$PATH${cX}"

